// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

export class DbHubInfo {
    version      : string;
    hostName?    : string | null;
    description? : string | null;
    website?     : string | null;
}

export class DbContainers {
    id            : string;
    databaseType  : string;
    containers    : string[];
}

export class DbCommands {
    id        : string;
    commands  : string[];
}

export class DbSchema {
    id           : string;
    schemaName   : string;
    schemaPath   : string;
    jsonSchemas  : { [key: string]: any };
}

export class DbList {
    databases  : DbContainers[];
}

