// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

/** GUID / UUID as RFC 4122. e.g. "123e4567-e89b-12d3-a456-426614174000" */
export type Guid = string;

/** signed integer 32-bit. Range: [-2147483648, 2147483647]                   */
export type int32 = number;

/** timestamp as RFC 3339 + milliseconds   */
export type DateTime = string;

/** integer with arbitrary precision       */
export type BigInteger = string;

/** unsigned integer 8-bit. Range: [0 - 255]                                  */
export type uint8 = number;

/** signed integer 16-bit. Range: [-32768, 32767]                             */
export type int16 = number;

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807] */
export type int64 = number;

/** single precision floating point number */
export type float = number;

/** double precision floating point number */
export type double = number;

