// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
import { Guid } from "./Standard"

export abstract class EntityIdStore {
    guidEntities  : { [key: string]: GuidEntity };
}

export class GuidEntity {
    id  : Guid;
}

