// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
import { Guid }  from "./Standard"
import { int32 } from "./Standard"
import { int64 } from "./Standard"

export abstract class EntityIdStore {
    guidEntities  : { [key: string]: GuidEntity };
    intEntities   : { [key: string]: IntEntity };
    longEntities  : { [key: string]: LongEntity };
}

export class GuidEntity {
    id  : Guid;
}

export class IntEntity {
    id  : int32;
}

export class LongEntity {
    id  : int64;
}

