// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package Friflo.Json.Flow.Sync

import kotlinx.serialization.*

enum class TaskType {
    read,
    query,
    create,
    update,
    patch,
    delete,
    message,
    subscribeChanges,
    subscribeMessage,
    error,
}

enum class Change {
    create,
    update,
    patch,
    delete,
}

