// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package UserStore.Graph

import kotlinx.serialization.*

@Serializable
abstract class Entity {
    abstract  val id : String
}

