// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package UserStore.Auth.Rights

import kotlinx.serialization.*
import CustomSerializer.BigIntegerSerializer
import UserStore.Sync.*

@Serializable
sealed class Right {
    abstract  val description : String?
}

@Serializable
@SerialName("allow")
data class RightAllow (
              val grant       : Boolean,
    override  val description : String? = null,
) : Right()

@Serializable
@SerialName("task")
data class RightTask (
              val types       : List<TaskType>,
    override  val description : String? = null,
) : Right()

@Serializable
@SerialName("message")
data class RightMessage (
              val names       : List<String>,
    override  val description : String? = null,
) : Right()

@Serializable
@SerialName("subscribeMessage")
data class RightSubscribeMessage (
              val names       : List<String>,
    override  val description : String? = null,
) : Right()

@Serializable
@SerialName("database")
data class RightDatabase (
              val containers  : HashMap<String, ContainerAccess>,
    override  val description : String? = null,
) : Right()

@Serializable
data class ContainerAccess (
              val operations       : List<OperationType>? = null,
              val subscribeChanges : List<Change>? = null,
)

enum class OperationType {
    create,
    update,
    delete,
    patch,
    read,
    query,
    mutate,
    full,
}

@Serializable
@SerialName("predicate")
data class RightPredicate (
              val names       : List<String>,
    override  val description : String? = null,
) : Right()

