// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
import { DbInfo }       from "./Friflo.Json.Fliox.Hub.DB.Cluster"
import { DbContainers } from "./Friflo.Json.Fliox.Hub.DB.Cluster"
import { DbCommands }   from "./Friflo.Json.Fliox.Hub.DB.Cluster"
import { DbSchema }     from "./Friflo.Json.Fliox.Hub.DB.Cluster"
import { DbList }       from "./Friflo.Json.Fliox.Hub.DB.Cluster"
import { Right }        from "./Friflo.Json.Fliox.Hub.Host.Auth.Rights"
import { Right_Union }  from "./Friflo.Json.Fliox.Hub.Host.Auth.Rights"

export abstract class UserStore {
    credentials  : { [key: string]: UserCredential };
    permissions  : { [key: string]: UserPermission };
    roles        : { [key: string]: Role };

    // commands
    AuthenticateUser (param: AuthenticateUser) : AuthenticateUserResult;
    DbInfo           (param: any) : DbInfo;
    DbContainers     (param: any) : DbContainers;
    DbCommands       (param: any) : DbCommands;
    DbSchema         (param: any) : DbSchema;
    DbList           (param: any) : DbList;
    DbEcho           (param: any) : any;
}

export class UserCredential {
    id        : string;
    passHash? : string | null;
    token?    : string | null;
}

export class UserPermission {
    id     : string;
    roles? : string[] | null;
}

export class Role {
    id           : string;
    rights       : Right_Union[];
    description? : string | null;
}

export class AuthenticateUser {
    userId  : string;
    token   : string;
}

export class AuthenticateUserResult {
    isValid  : boolean;
}

