// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

export class DbContainers {
    id            : string;
    databaseType  : string;
    containers    : string[];
    commands      : string[];
}

export class DbSchema {
    id           : string;
    schemaName   : string;
    schemaPath   : string;
    jsonSchemas  : { [key: string]: any };
}

export class DbList {
    databases  : DbContainers[];
}

