// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
import { int64 } from "./Standard";

export class DbContainers {
    id          : string;
    storage     : string;
    containers  : string[];
}

export class DbMessages {
    id        : string;
    commands  : string[];
    messages  : string[];
}

export class DbSchema {
    id           : string;
    schemaName   : string;
    schemaPath   : string;
    jsonSchemas  : { [key: string]: any };
}

export class DbStats {
    containers? : ContainerStats[] | null;
}

export class ContainerStats {
    name   : string;
    count  : int64;
}

export class HostDetails {
    version         : string;
    hostName?       : string | null;
    projectName?    : string | null;
    projectWebsite? : string | null;
    envName?        : string | null;
    /**
     * the color used to display the environment name in GUI's using CSS color format.  
     * E.g. using red for a production environment: "#ff0000" or "rgb(255 0 0)"
     */
    envColor?       : string | null;
}

export class HostCluster {
    databases  : DbContainers[];
}

