// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

export type TaskType =
    | "read"
    | "query"
    | "create"
    | "upsert"
    | "patch"
    | "delete"
    | "aggregate"
    | "message"
    | "command"
    | "closeCursors"
    | "subscribeChanges"
    | "subscribeMessage"
    | "reserveKeys"
    | "error"
;

export type Change =
    | "create"
    | "upsert"
    | "patch"
    | "delete"
;

