// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** [OpenAPI Object specification](https://spec.openapis.org/oas/v3.0.0#openapi-object) */
export class OpenApi {
    version?        : string | null;
    termsOfService? : string | null;
    info?           : OpenApiInfo | null;
    servers?        : OpenApiServer[] | null;
}

export class OpenApiInfo {
    contact? : OpenApiContact | null;
    license? : OpenApiLicense | null;
}

export class OpenApiContact {
    name?  : string | null;
    url?   : string | null;
    email? : string | null;
}

export class OpenApiLicense {
    name? : string | null;
    url?  : string | null;
}

export class OpenApiServer {
    url?         : string | null;
    description? : string | null;
}

