// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** [OpenAPI Object specification](https://spec.openapis.org/oas/v3.0.0#openapi-object) */
export class OpenAPI {
    version? : string | null;
    info?    : OpenAPIInfo | null;
    servers? : OpenAPIServer[] | null;
}

export class OpenAPIInfo {
    contact? : OpenAPIContact | null;
    license? : OpenAPILicense | null;
}

export class OpenAPIContact {
    name?  : string | null;
    url?   : string | null;
    email? : string | null;
}

export class OpenAPILicense {
    name? : string | null;
    url?  : string | null;
}

export class OpenAPIServer {
    url?         : string | null;
    description? : string | null;
}

