// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807] */
export type int64 = number;

