
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox

###
GET {{base}}/explorer
Cookie: {{auth}}

###
GET {{base}}/swagger
Cookie: {{auth}}

###
GET {{base}}/graphiql
Cookie: {{auth}}


###
GET {{base}}/examples
Cookie: {{auth}}




