
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox

###
GET {{base}}/rest/main_db/articles/article-1
Cookie: {{auth}}


###
GET {{base}}/rest/main_db?command=std.Messages
Cookie: {{auth}}






