// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
import { Guid }  from "./Standard"
import { int32 } from "./Standard"
import { int64 } from "./Standard"
import { int16 } from "./Standard"
import { uint8 } from "./Standard"

export abstract class EntityIdStore {
    guidEntities       : { [key: string]: GuidEntity };
    guidNullEntities   : { [key: string]: GuidNullEntity };
    intEntities        : { [key: string]: IntEntity };
    longEntities       : { [key: string]: LongEntity };
    shortEntities      : { [key: string]: ShortEntity };
    byteEntities       : { [key: string]: ByteEntity };
    customIdEntities   : { [key: string]: CustomIdEntity };
    entityRefs         : { [key: string]: EntityRefs };
    customIdEntities2  : { [key: string]: CustomIdEntity2 };
}

export class GuidEntity {
    id  : Guid;
}

export class GuidNullEntity {
    id? : Guid | null;
}

export class IntEntity {
    id  : int32;
}

export class LongEntity {
    Id  : int64;
}

export class ShortEntity {
    id  : int16;
}

export class ByteEntity {
    id  : uint8;
}

export class CustomIdEntity {
    customId  : string;
}

export class EntityRefs {
    id              : string;
    guidEntity      : Guid;
    guidNullEntity? : Guid | null;
    intEntity       : int32;
    longEntity      : int64;
    shortEntity     : int16;
    byteEntity      : uint8;
    customIdEntity? : string | null;
    intEntities?    : int32[] | null;
}

export class CustomIdEntity2 {
    customId2  : string;
}

