@base = http://localhost:8010/fliox


###
GET {{base}}/rest/user_db?cmd=ValidateUserDb
Cookie: fliox-user=admin; fliox-token=admin

###
GET {{base}}/rest/user_db?cmd=ValidateUserDb
Cookie: fliox-user=user-admin; fliox-token=user-admin
