// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
import { int32 } from "./Standard"

export class RequestCount {
    db?       : string | null;
    requests  : int32;
    tasks     : int32;
}

