// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** Filter type used to specify the type of a database change. */
export type Change =
    | "create"
    | "upsert"
    | "patch"
    | "delete"
;

