// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

/** signed integer 32-bit. Range: [-2147483648, 2147483647]                   */
export type int32 = number;

