// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** timestamp as RFC 3339 + milliseconds   */
export type DateTime = string;

/** signed integer 32-bit. Range: [-2147483648, 2147483647]                   */
export type int32 = number;

/** integer with arbitrary precision       */
export type BigInteger = string;

/** unsigned integer 8-bit. Range: [0 - 255]                                  */
export type uint8 = number;

/** signed integer 16-bit. Range: [-32768, 32767]                             */
export type int16 = number;

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807]
 *  number in JavaScript.  Range: [-9007199254740991, 9007199254740991]       */
export type int64 = number;

/** single precision floating point number */
export type float = number;

/** double precision floating point number */
export type double = number;

/** unsigned integer 8-bit. Range: [-128 - 127]                               */
export type uint8 = number;

/** signed integer 16-bit. Range: [0, 65535]                                  */
export type int16 = number;

/** signed integer 32-bit. Range: [0, 4294967295]                             */
export type int32 = number;

/** signed integer 64-bit. Range: [0, 18446744073709551615]
 *  number in JavaScript.  Range: [0, 9007199254740991]                       */
export type int64 = number;

/** array of arrays"                      */
export type JsonTable = any[][];

