// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export type TaskType =
    | "read"
    | "query"
    | "create"
    | "update"
    | "patch"
    | "delete"
    | "message"
    | "subscribeChanges"
    | "subscribeMessage"
    | "error"
;

export type Change =
    | "create"
    | "update"
    | "patch"
    | "delete"
;

