// Copyright (c) Ullrich Praetz. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Friflo.Json.Flow.Schema.Definition;
using Friflo.Json.Flow.Schema.Utils;

namespace Friflo.Json.Flow.Schema
{
    /// <summary>
    /// A context class required to be used for all code / schema generators.<br></br>
    /// Examples available at:
    /// <see href="https://github.com/friflo/Friflo.Json.Flow/blob/main/Json.Tests/Common/UnitTest/Flow/Schema/GenerateSchema.cs"/>
    /// <br></br>
    /// 
    /// It contains the configuration for schema generation and the result after schema generation was executed.
    /// The main configuration consists of the types to be generated and the file extension for generated files.
    /// The result consists of the generated source <see cref="files"/>.
    /// The utility method <see cref="WriteFiles"/> enables writing these files to a folder.
    /// 
    /// <br></br>
    /// In case of adding an additional code generator which should be part of this project the following
    /// requirements must be met:
    /// <list type="bullet">
    ///   <item>
    ///     No dependencies to third party libraries. E.g. Serializer libraries to create a specific format (YAML, ...)
    ///     Schema / code generators are forced to use <see cref="StringBuilder"/> like in <see cref="Typescript"/>     
    ///   </item>
    ///   <item>
    ///     A code generator must not have any mutable state. All used properties must be readonly immutables.
    ///   </item>
    ///   <item>
    ///     Avoid virtual methods or interfaces to establish simplicity. 
    ///   </item>
    ///   <item>
    ///     As initial template <see cref="Typescript"/> or <see cref="JsonSchema"/> need to be used to ensure the resulting
    ///     generator can be compared to their originals with tools like WinMerge.
    ///     In particular the methods and their order <see cref="Typescript.GenerateSchema"/>, <see cref="Typescript.EmitType"/>,
    ///     <see cref="Typescript.GetFieldType"/> and <see cref="Typescript.EmitFileHeaders"/>.
    ///     Helper methods need to be added on the bottom.
    ///   </item>
    ///   <item>
    ///     The implementation should be small similar to <see cref="Typescript"/> and <see cref="JsonSchema"/>
    ///   </item>
    ///   <item>
    ///     The generated files (PocStore and Sync) must be committed to a folder in 'assets/Schema' and
    ///     a lean setup should be added ensuring the generated files are valid / compile successful.
    ///   </item>
    /// </list>
    /// </summary>
    public class Generator
    {
        public   readonly   string                          fileExt;
        
        public   readonly   TypeSchema                      schema;


        /// map of all <see cref="TypeDef"/>'s required by the types provided for schema generation
        public   readonly   ICollection<TypeDef>            types;
        /// map of all generated files. key: file path  
        public   readonly   Dictionary<string, EmitFile>    emitFiles       = new Dictionary<string, EmitFile>();
        /// set of generated files and their source content. key: file name
        public   readonly   Dictionary<string, string>      files           = new Dictionary<string, string>();
        /// set of files where each type is generated into a separate file
        public   readonly   ICollection<TypeDef>            separateTypes;
        
        // --- private
        /// map of all emitted types and their emitted code 
        private  readonly   Dictionary<TypeDef, EmitType>   emitTypes       = new Dictionary<TypeDef, EmitType>();
        private  readonly   ICollection<string>             stripNamespaces;

        public const string Note = "Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema";

        public Generator (TypeSchema schema, ICollection<string> stripNamespaces, string fileExtension, Func<TypeDef, string> getPath = null) {
            this.schema             = schema;
            fileExt                 = fileExtension;
            types                   = schema.Types;
            this.stripNamespaces    = stripNamespaces       ?? new List<string>();
            separateTypes           = schema.SeparateTypes  ?? new List<TypeDef>();
            
            getPath = getPath ?? GetPathCallback;
            foreach (var type in types) {
                var path    = getPath(type);
                path        = Strip(path);
                type.Path   = path;
            }
        }
        
        private string Strip (string ns) {
            ns  = ns ?? "default";
            foreach (var stripNamespace in stripNamespaces) {
                var pos = ns.IndexOf(stripNamespace, StringComparison.InvariantCulture);
                if (pos == 0) {
                    return ns.Substring(stripNamespace.Length);
                }
            }
            return ns;
        }
        
        private string GetPathCallback(TypeDef type) {
            if (separateTypes.Contains(type)) {
                return $"{type.Namespace}.{type.Name}";
            }
            return type.Namespace;
        }
        
        public static void AddType (Dictionary<TypeDef, string> types, TypeDef type, string value) {
            if (type == null)
                return;
            types.Add(type, value);
        }
        
        // ---------------------------------- output generation  ----------------------------------
        public void AddEmitType(EmitType emit) {
            emitTypes.TryAdd(emit.type, emit);
        }
        
        public void GroupTypesByPath(bool sortDependencies) {
            ICollection<EmitType> emits;
            if (sortDependencies) {
                emits = SortDependencies();
            } else {
                emits = emitTypes.Values;
            }
            foreach (var emit in emits) {
                var filePath = emit.path;
                if (!emitFiles.TryGetValue(filePath, out var emitFile)) {
                    emitFiles.Add(filePath, emitFile = new EmitFile(filePath));
                }
                emitFile.emitTypes.Add(emit);
                foreach (var type in emit.imports) {
                    if (emitFile.imports.Contains(type))
                        continue;
                    emitFile.imports.Add(type);
                }
            }
        }
        
        public void GroupToSingleFile(string name) {
            ICollection<EmitType> emits = emitTypes.Values;
            var emitFile = new EmitFile($"{name}{fileExt}");
            emitFiles.Add(name, emitFile);
            foreach (var emit in emits) {
                emitFile.emitTypes.Add(emit);
            }
        }
        
        private ICollection<EmitType> SortDependencies() {
            foreach (var pair in emitTypes) {
                var emitType = pair.Value;
                foreach (var type in emitType.typeDependencies) {
                    var emitDependency = emitTypes[type];
                    emitType.emitDependencies.Add(emitDependency);
                }
            }
            return TopologicalSort.Sort(emitTypes.Values, x => x.emitDependencies);
        }
        
        public static string Indent(int max, string str) {
            return new string(' ', Math.Max(max - str.Length, 0));
        }
        
        public static void Delimiter (StringBuilder sb, string delimiter, ref bool first) {
            if (first) {
                first = false;
                return;
            }
            sb.Append(delimiter);
        }
        
        public void CreateFiles(StringBuilder sb, Func<string, string> toFilename, string delimiter = null) {
            foreach (var pair in emitFiles) {
                string      path        = pair.Key;
                EmitFile    emitFile    = pair.Value;
                sb.Clear();
                sb.AppendLine(emitFile.header);
                bool first = true;
                foreach (var result in emitFile.emitTypes) {
                    if (delimiter != null)
                        Delimiter(sb, delimiter, ref first);
                    sb.Append(result.content);
                }
                if (emitFile.footer != null)
                    sb.AppendLine(emitFile.footer);
                var filename = toFilename(path);
                files.Add(filename, sb.ToString());
            }
        }
        
        /// <summary>
        /// Write the generated file to the given folder and remove all others file with the used <see cref="fileExt"/>
        /// </summary>
        public void WriteFiles(string folder, bool cleanFolder = true) {
            // folder = Path.GetFullPath (folder);
            folder = folder.Replace('\\', '/');
            Directory.CreateDirectory(folder);
            string[] fileNames = Directory.GetFiles(folder, $"*{fileExt}", SearchOption.TopDirectoryOnly);
            for (int i = 0; i < fileNames.Length; i++) { fileNames[i] = fileNames[i].Replace('\\', '/'); }
            var fileSet = new HashSet<string>(fileNames);
            var utf8    = new UTF8Encoding(false);
            foreach (var file in files) {
                var filename    = file.Key;
                var content     = file.Value;
                var path        = $"{folder}/{filename}";
                fileSet.Remove(path);
                var lastSlash   = path.LastIndexOf("/", StringComparison.InvariantCulture);
                var fileFolder  = lastSlash == -1 ? folder : path.Substring(0, lastSlash);
                Directory.CreateDirectory(fileFolder);
                File.WriteAllText(path, content, utf8);
            }
            if (!cleanFolder)
                return;
            foreach (var fileName in fileSet) {
                File.Delete(fileName);
            }
        }
    }
}