// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

export type TaskType =
    | "read"
    | "query"
    | "create"
    | "upsert"
    | "patch"
    | "delete"
    | "aggregate"
    | "message"
    | "command"
    | "closeCursors"
    | "subscribeChanges"
    | "subscribeMessage"
    | "reserveKeys"
    | "error"
;

export type Change =
    | "create"      /** Filter database change events of new created entities. */
    | "upsert"      /** Filter database change events of upserted entities. */
    | "patch"      /** Filter database change events used to patch entities. */
    | "delete"      /** Filter database change events used to delete entities. */
;

