// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

/** double precision floating point number */
export type double = number;

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807]
 *  number in JavaScript.  Range: [-9007199254740991, 9007199254740991]       */
export type int64 = number;

