// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
using System.Collections.Generic;
using Friflo.Json.Flow.Mapper;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace UserStore2.Sync {

public enum TaskType {
    read,
    query,
    create,
    update,
    patch,
    delete,
    message,
    subscribeChanges,
    subscribeMessage,
    error,
}

public enum Change {
    create,
    update,
    patch,
    delete,
}

}

