// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export type DateTime = string;

export type int32 = number;

export type BigInteger = string;

export type uint8 = number;

export type int16 = number;

export type int64 = number;

export type float = number;

export type double = number;

export class Article {
    id        : string;
    name      : string;
    producer? : string | null;
}

export class Customer {
    id    : string;
    name  : string;
}

export class Employee {
    id         : string;
    firstName  : string;
    lastName?  : string | null;
}

export class OrderItem {
    article  : string;
    amount   : int32;
    name?    : string | null;
}

export class PocStruct {
    val  : int32;
}

export class DerivedClass extends OrderItem {
    derivedVal  : int32;
}

export class Order {
    id        : string;
    customer? : string | null;
    created   : DateTime;
    items?    : OrderItem[] | null;
}

export class Producer {
    id         : string;
    name       : string;
    employees? : string | null;
}

export class TestType {
    id                : string;
    dateTime          : DateTime;
    dateTimeNull?     : string | null;
    bigInt            : BigInteger;
    bigIntNull?       : string | null;
    boolean           : boolean;
    booleanNull?      : boolean | null;
    uint8             : uint8;
    uint8Null?        : string | null;
    int16             : int16;
    int16Null?        : string | null;
    int32             : int32;
    int32Null?        : string | null;
    int64             : int64;
    int64Null?        : string | null;
    float32           : float;
    float32Null?      : string | null;
    float64           : double;
    float64Null?      : string | null;
    pocStruct         : PocStruct;
    pocStructNull?    : string | null;
    intArray          : int32[];
    intArrayNull?     : int32[] | null;
    jsonValue         : {} | null;
    derivedClass      : DerivedClass;
    derivedClassNull? : string | null;
}

