// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package PocStore.Graph

import kotlinx.serialization.*
import CustomSerializer.BigIntegerSerializer

@Serializable
abstract class Entity {
    abstract  val id : String
}

