// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package PocStore.Graph

import kotlinx.serialization.*
import CustomSerializer.BigIntegerSerializer
import kotlinx.datetime.*
import java.math.*
import kotlinx.serialization.json.*

@Serializable
data class Order (
    override  val id       : String,
              val customer : String? = null,
              val created  : Instant,
              val items    : List<OrderItem>? = null,
) : Entity()

@Serializable
abstract class Entity {
    abstract  val id : String
}

@Serializable
data class OrderItem (
              val article : String,
              val amount  : Int,
              val name    : String? = null,
)

@Serializable
data class Customer (
    override  val id   : String,
              val name : String,
) : Entity()

@Serializable
data class Article (
    override  val id       : String,
              val name     : String,
              val producer : String? = null,
) : Entity()

@Serializable
data class Producer (
    override  val id        : String,
              val name      : String,
              val employees : List<String>? = null,
) : Entity()

@Serializable
data class Employee (
    override  val id        : String,
              val firstName : String,
              val lastName  : String? = null,
) : Entity()

@Serializable
data class TestType (
    override  val id               : String,
              val dateTime         : Instant,
              val dateTimeNull     : Instant? = null,
              @Serializable(with = BigIntegerSerializer::class)
              val bigInt           : BigInteger,
              @Serializable(with = BigIntegerSerializer::class)
              val bigIntNull       : BigInteger? = null,
              val boolean          : Boolean,
              val booleanNull      : Boolean? = null,
              val uint8            : Byte,
              val uint8Null        : Byte? = null,
              val int16            : Short,
              val int16Null        : Short? = null,
              val int32            : Int,
              val int32Null        : Int? = null,
              val int64            : Long,
              val int64Null        : Long? = null,
              val float32          : Float,
              val float32Null      : Float? = null,
              val float64          : Double,
              val float64Null      : Double? = null,
              val pocStruct        : PocStruct,
              val pocStructNull    : PocStruct? = null,
              val intArray         : List<Int>,
              val intArrayNull     : List<Int>? = null,
              val jsonValue        : JsonElement? = null,
              val derivedClass     : DerivedClass,
              val derivedClassNull : DerivedClass? = null,
) : Entity()

@Serializable
data class PocStruct (
              val value : Int,
)

@Serializable
data class DerivedClass (
              val derivedVal : Int,
              val article    : String,
              val amount     : Int,
              val name       : String? = null,
)

