// Copyright (c) Ullrich Praetz. All rights reserved.
// See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Friflo.Json.Fliox.Graph.Internal.Map
{
    internal static class StoreUtils
    {
        internal static Type[] GetEntityTypes<TEntityStore>() where TEntityStore : EntityStore 
        {
            var types   = new List<Type>();
            var type    = typeof(TEntityStore);
            var flags   = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;
            PropertyInfo[] properties = type.GetProperties(flags);
            for (int n = 0; n < properties.Length; n++) {
                var  property       = properties[n];
                Type propType       = property.PropertyType;
                bool isEntitySet    = IsEntitySet(propType);
                if (!isEntitySet)
                    continue;
                var genericArgs = propType.GetGenericArguments();
                var entityType = genericArgs[1];
                types.Add(entityType);
            }
            FieldInfo[] fields = type.GetFields(flags);
            for (int n = 0; n < fields.Length; n++) {
                var  field          = fields[n];
                Type fieldType      = field.FieldType;
                bool isEntitySet    = IsEntitySet(fieldType);
                if (!isEntitySet || IsAutoGeneratedBackingField(field))
                    continue;
                var genericArgs = fieldType.GetGenericArguments();
                var entityType = genericArgs[1];
                types.Add(entityType);
            }
            return types.ToArray();
        }

        internal static void InitEntitySets(EntityStore store) {
            var type    = store.GetType();
            var flags   = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;
            PropertyInfo[] properties = type.GetProperties(flags);
            for (int n = 0; n < properties.Length; n++) {
                var  property       = properties[n];
                Type propType       = property.PropertyType;
                bool isEntitySet    = IsEntitySet(propType);
                if (!isEntitySet)
                    continue;
                var setMapper   = (IEntitySetMapper)store._intern.typeStore.GetTypeMapper(propType);
                var entitySet   = setMapper.CreateEntitySet();
                property.SetValue(store, entitySet);
                entitySet.Init(store);
            }
            FieldInfo[] fields = type.GetFields(flags);
            for (int n = 0; n < fields.Length; n++) {
                var  field          = fields[n];
                Type fieldType      = field.FieldType;
                bool isEntitySet    = IsEntitySet(fieldType);
                if (!isEntitySet || IsAutoGeneratedBackingField(field))
                    continue;
                var setMapper   = (IEntitySetMapper)store._intern.typeStore.GetTypeMapper(fieldType);
                var entitySet   = setMapper.CreateEntitySet();
                field.SetValue(store, entitySet);
                entitySet.Init(store);
            }
        }
        
        internal static bool IsEntitySet (Type type) {
            return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(EntitySet<,>);
        }
        
        private static bool IsAutoGeneratedBackingField(FieldInfo field) {
            foreach (CustomAttributeData attr in field.CustomAttributes) {
                if (attr.AttributeType == typeof(CompilerGeneratedAttribute))
                    return true;
            }
            return false;
        }
    }
}