// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export class UserCredential {
    id        : string;
    passHash? : string | null;
    token?    : string | null;
}

