// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
using System.Collections.Generic;
using Friflo.Json.Fliox.Mapper;
using UserStore2.Hub.Host.Auth.Rights;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace UserStore2.Hub.DB.UserAuth {

public class UserCredential {
    [Fri.Required]
    string  id;
    string  token;
}

public class UserPermission {
    [Fri.Required]
    string        id;
    List<string>  roles;
}

public class Role {
    [Fri.Required]
    string       id;
    [Fri.Required]
    List<Right>  rights;
    string       description;
}

}

