// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
using System.Collections.Generic;
using Friflo.Json.Fliox.Mapper;
using UserStore2.Hub.Host.Auth.Rights;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace UserStore2.Hub.DB.UserAuth {

public abstract class UserStore {
    [Fri.RequiredMember]
    Dictionary<string, UserCredential>  credentials;
    [Fri.RequiredMember]
    Dictionary<string, UserPermission>  permissions;
    [Fri.RequiredMember]
    Dictionary<string, Role>            roles;
}

public class UserCredential {
    [Fri.RequiredMember]
    string  id;
    string  token;
}

public class UserPermission {
    [Fri.RequiredMember]
    string        id;
    List<string>  roles;
}

public class Role {
    [Fri.RequiredMember]
    string       id;
    [Fri.RequiredMember]
    List<Right>  rights;
    string       description;
}

public class Credentials {
    [Fri.RequiredMember]
    string  userId;
    [Fri.RequiredMember]
    string  token;
}

public class AuthResult {
    bool  isValid;
}

public class ValidateUserDbResult {
    List<string>  errors;
}

}

