// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Friflo.Json.Fliox;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace UserStore2.Hub.Protocol.Tasks {

public enum TaskType {
    read,
    query,
    create,
    upsert,
    patch,
    merge,
    delete,
    aggregate,
    message,
    command,
    closeCursors,
    subscribeChanges,
    subscribeMessage,
    reserveKeys,
    error,
}

public enum EntityChange {
    create,
    upsert,
    patch,
    merge,
    delete,
}

}

