// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** Implement models of RFC 6902  [JavaScript Object Notation (JSON) Patch](https://tools.ietf.org/html/rfc6902) */
export type JsonPatch_Union =
    | PatchReplace
    | PatchAdd
    | PatchRemove
    | PatchCopy
    | PatchMove
    | PatchTest
;

export abstract class JsonPatch {
    /** patch type */
    abstract op:
        | "replace"
        | "add"
        | "remove"
        | "copy"
        | "move"
        | "test"
    ;
}

export class PatchReplace extends JsonPatch {
    /** patch type */
    op     : "replace";
    path   : string;
    value  : any;
}

export class PatchAdd extends JsonPatch {
    /** patch type */
    op     : "add";
    path   : string;
    value  : any;
}

export class PatchRemove extends JsonPatch {
    /** patch type */
    op    : "remove";
    path  : string;
}

export class PatchCopy extends JsonPatch {
    /** patch type */
    op    : "copy";
    path  : string;
    from? : string | null;
}

export class PatchMove extends JsonPatch {
    /** patch type */
    op    : "move";
    path  : string;
    from? : string | null;
}

export class PatchTest extends JsonPatch {
    /** patch type */
    op     : "test";
    path   : string;
    value? : any | null;
}

