// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
import { int32 } from "./Standard";

/**
 * Specify the **ids** requested by a **ReadEntities** task.  
 * To return entities referenced by fields of the read result use **references**
 */
export class ReadEntitiesSet {
    ids         : string[];
    references? : References[] | null;
}

/** **References** are used to return entities referenced by fields of entities returned by read and query tasks.  **References** can be nested to return referenced entities of referenced entities. */
export class References {
    /** the path to field used as a reference to an entity in the specified **container** */
    selector    : string;
    /** the **container** storing the entities referenced by the specified **selector** */
    container   : string;
    keyName?    : string | null;
    isIntKey?   : boolean | null;
    references? : References[] | null;
}

export class ReadEntitiesSetResult {
    references? : ReferencesResult[] | null;
}

export class ReferencesResult {
    error?      : string | null;
    container?  : string | null;
    /**
     * Is used only to show the number of **ids** in a serialized protocol message
     * to avoid counting them by hand when debugging.
     * It is not used by the library as it is redundant information.
     */
    count?      : int32 | null;
    ids         : string[];
    references? : ReferencesResult[] | null;
}

export class EntityError {
    type     : EntityErrorType;
    message? : string | null;
}

export type EntityErrorType =
    | "Undefined"
    | "ParseError"
    | "ReadError"
    | "WriteError"
    | "DeleteError"
    | "PatchError"
;

