// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** Implement models of RFC 6902 - "JavaScript Object Notation (JSON) Patch".   JSON Patch RFC */
export type JsonPatch_Union =
    | PatchReplace
    | PatchAdd
    | PatchRemove
    | PatchCopy
    | PatchMove
    | PatchTest
;

export abstract class JsonPatch {
    abstract op:
        | "replace"
        | "add"
        | "remove"
        | "copy"
        | "move"
        | "test"
    ;
}

export class PatchReplace extends JsonPatch {
    op     : "replace";
    path   : string;
    value  : any;
}

export class PatchAdd extends JsonPatch {
    op     : "add";
    path   : string;
    value  : any;
}

export class PatchRemove extends JsonPatch {
    op    : "remove";
    path  : string;
}

export class PatchCopy extends JsonPatch {
    op    : "copy";
    path  : string;
    from? : string | null;
}

export class PatchMove extends JsonPatch {
    op    : "move";
    path  : string;
    from? : string | null;
}

export class PatchTest extends JsonPatch {
    op     : "test";
    path   : string;
    value? : any | null;
}

