// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** signed integer 32-bit. Range: [-2147483648, 2147483647]                   */
export type int32 = number;

/** GUID / UUID as RFC 4122. e.g. "123e4567-e89b-12d3-a456-426614174000" */
export type Guid = string;

/** generic key type for key/values"      */
export type JsonKey = string | number;

/** double precision floating point number */
export type double = number;

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807]
 *  number in JavaScript.  Range: [-9007199254740991, 9007199254740991]       */
export type int64 = number;

