// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema

/** signed integer 64-bit. Range: [-9223372036854775808, 9223372036854775807]
 *  number in JavaScript.  Range: [-9007199254740991, 9007199254740991]       */
export type int64 = number;

/** timestamp as RFC 3339 + milliseconds   */
export type DateTime = string;

/** signed integer 32-bit. Range: [-2147483648, 2147483647]                   */
export type int32 = number;

