// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export class Order {
    id        : string;
    customer? : string;
    items?    : OrderItem[];
}

export class OrderItem {
    article? : string;
    amount   : number;
    name?    : string;
}

export class Customer {
    id    : string;
    name? : string;
}

export class Article {
    id        : string;
    name?     : string;
    producer? : string;
}

export class Producer {
    id            : string;
    name?         : string;
    employeeList? : string[];
}

export class Employee {
    id         : string;
    firstName? : string;
    lastName?  : string;
}

