// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export type DateTime = string;

export type int32 = number;

export type BigInteger = string;

export type uint8 = number;

export type int16 = number;

export type int64 = number;

export type float = number;

export type double = number;

