// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
using System.Collections.Generic;
using System;
using System.Numerics;
using Friflo.Json.Flow.Mapper;

#pragma warning disable 0169

namespace UnitTest.Flow.Graph {

public class Order {
    string          id;
    string          customer;
    DateTime        created;
    List<OrderItem> items;
}

public class OrderItem {
    string article;
    int    amount;
    string name;
}

public class Customer {
    string id;
    string name;
}

public class Article {
    string id;
    string name;
    string producer;
}

public class Producer {
    string       id;
    string       name;
    List<string> employees;
}

public class Employee {
    string id;
    string firstName;
    string lastName;
}

public class TestType {
    string       id;
    DateTime     dateTime;
    DateTime     dateTimeNull;
    BigInteger   bigInt;
    BigInteger   bigIntNull;
    bool         boolean;
    bool         booleanNull;
    byte         uint8;
    byte         uint8Null;
    short        int16;
    short        int16Null;
    int          int32;
    int          int32Null;
    long         int64;
    long         int64Null;
    float        float32;
    float        float32Null;
    double       float64;
    double       float64Null;
    PocStruct    pocStruct;
    PocStruct    pocStructNull;
    List<int>    intArray;
    List<int>    intArrayNull;
    JsonValue    jsonValue;
    DerivedClass derivedClass;
    DerivedClass derivedClassNull;
}

public class PocStruct {
    int val;
}

public class DerivedClass : OrderItem {
    int derivedVal;
}

}

