// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export class Producer {
    id         : string;
    name       : string;
    employees? : string | null;
}

