// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export class Employee {
    id         : string;
    firstName  : string;
    lastName?  : string | null;
}

