// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export class Article {
    id        : string;
    name      : string;
    producer? : string | null;
}

