// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
import { int32 } from "./Standard"

export class OrderItem {
    article  : string;
    amount   : int32;
    name?    : string | null;
}

export class PocStruct {
    val  : int32;
}

export class DerivedClass extends OrderItem {
    derivedVal  : int32;
}

