
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox

###
PUT {{base}}/rest
Cookie: {{auth}}

###
GET {{base}}/rest/main_db//article-1
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/foo/?command=bar
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/foo/?command=bar
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/foo/?message=bar
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/foo/?message=bar
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/?command=std.Echo&param=invalid
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/articles/invalidOperation
Cookie: {{auth}}



