// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema

export type Right_Union =
    | RightAllow
    | RightTask
    | RightMessage
    | RightSubscribeMessage
    | RightDatabase
    | RightPredicate
;

export abstract class Right {
    abstract type:
        | "allow"
        | "task"
        | "message"
        | "subscribeMessage"
        | "database"
        | "predicate"
    ;
    description? : string | null;
}

export class RightAllow extends Right {
    type         : "allow";
    grant        : boolean;
}

export class RightTask extends Right {
    type         : "task";
    types        : TaskType[];
}

export class RightMessage extends Right {
    type         : "message";
    names        : string[];
}

export class RightSubscribeMessage extends Right {
    type         : "subscribeMessage";
    names        : string[];
}

export class RightDatabase extends Right {
    type         : "database";
    containers   : { [key: string]: ContainerAccess };
}

export class ContainerAccess {
    operations?       : OperationType[] | null;
    subscribeChanges? : Change[] | null;
}

export type OperationType =
    | "create"
    | "update"
    | "delete"
    | "patch"
    | "read"
    | "query"
    | "mutate"
    | "full"
;

export class RightPredicate extends Right {
    type         : "predicate";
    names        : string[];
}

export type TaskType =
    | "read"
    | "query"
    | "create"
    | "update"
    | "patch"
    | "delete"
    | "message"
    | "subscribeChanges"
    | "subscribeMessage"
    | "error"
;

export type Change =
    | "create"
    | "update"
    | "patch"
    | "delete"
;

export class Role {
    id           : string;
    rights       : Right_Union[];
    description? : string | null;
}

export class UserCredential {
    id        : string;
    passHash? : string | null;
    token?    : string | null;
}

export class UserPermission {
    id     : string;
    roles? : string | null;
}

