@base = http://localhost:8010/fliox

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [
    {
      "task":       "subscribeChanges",
      "cont":       "articles", 
      "changes": ["create", "upsert", "delete", "merge"]
    }
  ],
  "user":  "admin",
  "token": "admin"
}

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [
    {
      "task":     "subscribeMessage",
      "name":     "*",
      "remove":   false
    }
  ],
  "user":  "admin",
  "token": "admin"
}

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [
    {
      "task":     "invalidTaskType"
    }
  ]
}

###
POST {{base}}/

{
  "msg": "invalidMsgType",
  "tasks": [ ]
}

###
POST {{base}}/

{
  "msg": "sync"
}

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [ ],
  "user":  "admin",
  "token": "authFails"
}

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [
    {
      "task":  "message",
      "name":  "SomeMessage",
      "param": "Hello Message"
    }
  ],
  "user":  "admin",
  "token": "authFails"
}

###
POST {{base}}/

{
  "msg": "sync",
  "user":  "admin",
  "token": "admin"
}

###
POST {{base}}/

{
  "msg": "sync",
  "tasks": [null],
  "user":  "admin",
  "token": "admin"
}
