// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
package Default

import kotlinx.serialization.*
import CustomSerializer.*
import kotlinx.datetime.*

@Serializable
abstract class GlobalClient {
    abstract  val jobs : HashMap<String, GlobalJob>
}

@Serializable
data class GlobalJob (
              val id          : Long,
              val title       : String,
              val completed   : Boolean? = null,
              val created     : Instant? = null,
              val description : String? = null,
)

