// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
using System;
using System.Collections.Generic;
using System.Numerics;
using Flow.Auth.Rights;

#pragma warning disable 0169

namespace Flow.UserAuth {

public class Role {
    string      id;
    List<Right> rights;
    string      description;
}

public class UserCredential {
    string id;
    string passHash;
    string token;
}

public class UserPermission {
    string       id;
    List<string> roles;
}

}

