// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
using System;
using System.Collections.Generic;
using System.Numerics;

#pragma warning disable 0169

namespace Flow.Sync {

public enum TaskType {
    read,
    query,
    create,
    update,
    patch,
    delete,
    message,
    subscribeChanges,
    subscribeMessage,
    error,
}

public enum Change {
    create,
    update,
    patch,
    delete,
}

}

