// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package EntityIdStore.Graph

import kotlinx.serialization.*
import CustomSerializer.*
import java.util.*

@Serializable
data class GuidEntity (
              @Serializable(with = UUIDSerializer::class)
              val id : UUID,
)

@Serializable
data class IntEntity (
              val id : Int,
)

@Serializable
data class LongEntity (
              val Id : Long,
)

@Serializable
data class ShortEntity (
              val id : Short,
)

@Serializable
data class CustomIdEntity (
              val customId : String,
)

@Serializable
data class EntityRefs (
              val id             : String,
              val guidEntity     : String? = null,
              val intEntity      : String? = null,
              val longEntity     : String? = null,
              val shortEntity    : String? = null,
              val customIdEntity : String? = null,
              val guidEntities   : List<String>? = null,
)

@Serializable
data class CustomIdEntity2 (
              val customId2 : String,
)

