// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
package EntityIdStore.Graph

import kotlinx.serialization.*
import CustomSerializer.*
import java.util.*

@Serializable
data class GuidEntity (
              @Serializable(with = UUIDSerializer::class)
              val id : UUID,
)

