// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
import { int32 }                 from "./Standard"
import { FilterOperation }       from "./Friflo.Json.Fliox.Transform"
import { FilterOperation_Union } from "./Friflo.Json.Fliox.Transform"
import { JsonPatch }             from "./Friflo.Json.Fliox.Transform"
import { JsonPatch_Union }       from "./Friflo.Json.Fliox.Transform"

export class DatabaseMessage {
    req?  : DatabaseRequest_Union | null;
    resp? : DatabaseResponse_Union | null;
    ev?   : DatabaseEvent_Union | null;
}

export type DatabaseRequest_Union =
    | SyncRequest
;

export abstract class DatabaseRequest {
    abstract type:
        | "sync"
    ;
    reqId? : int32 | null;
}

export class SyncRequest extends DatabaseRequest {
    type    : "sync";
    client? : string | null;
    ack?    : int32 | null;
    token?  : string | null;
    tasks   : DatabaseTask_Union[];
}

export type DatabaseTask_Union =
    | CreateEntities
    | UpsertEntities
    | ReadEntitiesList
    | QueryEntities
    | PatchEntities
    | DeleteEntities
    | SendMessage
    | SubscribeChanges
    | SubscribeMessage
;

export abstract class DatabaseTask {
    abstract task:
        | "create"
        | "upsert"
        | "read"
        | "query"
        | "patch"
        | "delete"
        | "message"
        | "subscribeChanges"
        | "subscribeMessage"
    ;
}

export class CreateEntities extends DatabaseTask {
    task       : "create";
    container  : string;
    entities   : { [key: string]: EntityValue };
}

export class EntityValue {
    value? : any | null;
    error? : EntityError | null;
}

export class EntityError {
    type     : EntityErrorType;
    message? : string | null;
}

export type EntityErrorType =
    | "Undefined"
    | "ParseError"
    | "ReadError"
    | "WriteError"
    | "DeleteError"
    | "PatchError"
;

export class UpsertEntities extends DatabaseTask {
    task       : "upsert";
    container  : string;
    entities   : { [key: string]: EntityValue };
}

export class ReadEntitiesList extends DatabaseTask {
    task       : "read";
    container  : string;
    reads      : ReadEntities[];
}

export class ReadEntities {
    ids         : string[];
    references? : References[] | null;
}

export class References {
    selector    : string;
    container   : string;
    references? : References[] | null;
}

export class QueryEntities extends DatabaseTask {
    task        : "query";
    container   : string;
    filterLinq? : string | null;
    filter?     : FilterOperation_Union | null;
    references? : References[] | null;
}

export class PatchEntities extends DatabaseTask {
    task       : "patch";
    container  : string;
    patches    : { [key: string]: EntityPatch };
}

export class EntityPatch {
    patches  : JsonPatch_Union[];
}

export class DeleteEntities extends DatabaseTask {
    task       : "delete";
    container  : string;
    ids        : string[];
}

export class SendMessage extends DatabaseTask {
    task   : "message";
    name   : string;
    value  : any;
}

export class SubscribeChanges extends DatabaseTask {
    task       : "subscribeChanges";
    container  : string;
    changes    : Change[];
    filter?    : FilterOperation_Union | null;
}

export type Change =
    | "create"
    | "upsert"
    | "patch"
    | "delete"
;

export class SubscribeMessage extends DatabaseTask {
    task    : "subscribeMessage";
    name    : string;
    remove? : boolean | null;
}

export type DatabaseResponse_Union =
    | SyncResponse
    | ErrorResponse
;

export abstract class DatabaseResponse {
    abstract type:
        | "sync"
        | "error"
    ;
    reqId? : int32 | null;
}

export class SyncResponse extends DatabaseResponse {
    type          : "sync";
    error?        : ErrorResponse | null;
    tasks?        : TaskResult_Union[] | null;
    results?      : { [key: string]: ContainerEntities } | null;
    createErrors? : { [key: string]: EntityErrors } | null;
    updateErrors? : { [key: string]: EntityErrors } | null;
    patchErrors?  : { [key: string]: EntityErrors } | null;
    deleteErrors? : { [key: string]: EntityErrors } | null;
}

export class ErrorResponse extends DatabaseResponse {
    type     : "error";
    message? : string | null;
}

export type TaskResult_Union =
    | CreateEntitiesResult
    | UpsertEntitiesResult
    | ReadEntitiesListResult
    | QueryEntitiesResult
    | PatchEntitiesResult
    | DeleteEntitiesResult
    | SendMessageResult
    | SubscribeChangesResult
    | SubscribeMessageResult
    | TaskErrorResult
;

export abstract class TaskResult {
    abstract task:
        | "create"
        | "upsert"
        | "read"
        | "query"
        | "patch"
        | "delete"
        | "message"
        | "subscribeChanges"
        | "subscribeMessage"
        | "error"
    ;
}

export class CreateEntitiesResult extends TaskResult {
    task   : "create";
    Error? : CommandError | null;
}

export class CommandError {
    message? : string | null;
}

export class UpsertEntitiesResult extends TaskResult {
    task   : "upsert";
    Error? : CommandError | null;
}

export class ReadEntitiesListResult extends TaskResult {
    task   : "read";
    reads  : ReadEntitiesResult[];
}

export class ReadEntitiesResult {
    Error?      : CommandError | null;
    references  : ReferencesResult[];
}

export class ReferencesResult {
    error?      : string | null;
    container?  : string | null;
    ids         : string[];
    references? : ReferencesResult[] | null;
}

export class QueryEntitiesResult extends TaskResult {
    task        : "query";
    Error?      : CommandError | null;
    container?  : string | null;
    filterLinq? : string | null;
    ids         : string[];
    references? : ReferencesResult[] | null;
}

export class PatchEntitiesResult extends TaskResult {
    task   : "patch";
    Error? : CommandError | null;
}

export class DeleteEntitiesResult extends TaskResult {
    task   : "delete";
    Error? : CommandError | null;
}

export class SendMessageResult extends TaskResult {
    task    : "message";
    Error?  : CommandError | null;
    result? : any | null;
}

export class SubscribeChangesResult extends TaskResult {
    task  : "subscribeChanges";
}

export class SubscribeMessageResult extends TaskResult {
    task  : "subscribeMessage";
}

export class TaskErrorResult extends TaskResult {
    task        : "error";
    type        : TaskErrorResultType;
    message?    : string | null;
    stacktrace? : string | null;
}

export type TaskErrorResultType =
    | "None"
    | "UnhandledException"
    | "DatabaseError"
    | "InvalidTask"
    | "PermissionDenied"
    | "SyncError"
;

export class ContainerEntities {
    container? : string | null;
    entities   : { [key: string]: EntityValue };
}

export class EntityErrors {
    container? : string | null;
    errors     : { [key: string]: EntityError };
}

export type DatabaseEvent_Union =
    | SubscriptionEvent
;

export abstract class DatabaseEvent {
    abstract type:
        | "subscription"
    ;
    seq     : int32;
    target? : string | null;
    client? : string | null;
}

export class SubscriptionEvent extends DatabaseEvent {
    type    : "subscription";
    tasks?  : DatabaseTask_Union[] | null;
}

