// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema

export abstract class ClusterStore {
    catalogs  : { [key: string]: CatalogDatabase };
    schemas   : { [key: string]: CatalogSchema };
}

export interface ClusterStoreService {
    Catalog       (value: any) : CatalogDatabase;
    CatalogSchema (value: any) : CatalogSchema;
    CatalogList   (value: any) : CatalogList;
    Echo          (value: any) : any;
}

export class CatalogDatabase {
    id            : string;
    databaseType  : string;
    containers    : string[];
    commands      : string[];
}

export class CatalogSchema {
    id           : string;
    schemaName   : string;
    schemaPath   : string;
    jsonSchemas  : { [key: string]: any };
}

export class CatalogList {
    catalogs  : CatalogDatabase[];
}

