// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
package UserStore.DB.Protocol

import kotlinx.serialization.*
import CustomSerializer.*

enum class TaskType {
    read,
    query,
    create,
    upsert,
    patch,
    delete,
    message,
    subscribeChanges,
    subscribeMessage,
    reserveKeys,
    error,
}

enum class Change {
    create,
    upsert,
    patch,
    delete,
}

