// Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema
package UserStore.UserAuth

import kotlinx.serialization.*
import CustomSerializer.*
import UserStore.Auth.Rights.*

@Serializable
data class UserPermission (
              val id    : String,
              val roles : List<String>? = null,
)

@Serializable
data class UserCredential (
              val id       : String,
              val passHash : String? = null,
              val token    : String? = null,
)

@Serializable
data class Role (
              val id          : String,
              val rights      : List<Right>,
              val description : String? = null,
)

