// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
package UserStore.Hub.DB.UserAuth

import kotlinx.serialization.*
import CustomSerializer.*
import UserStore.Hub.Host.Auth.Rights.*

@Serializable
data class UserCredential (
              val id    : String,
              val token : String? = null,
)

@Serializable
data class UserPermission (
              val id    : String,
              val roles : List<String>? = null,
)

@Serializable
data class Role (
              val id          : String,
              val rights      : List<Right>,
              val description : String? = null,
)

