// Generated by: https://github.com/friflo/Friflo.Json.Flow/tree/main/Json/Flow/Schema
using System.Collections.Generic;
using Friflo.Json.Flow.Mapper;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace UserStore2.Graph {

public abstract class Entity {
    [Fri.Required]
    string  id;
}

}

