// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
using System.Collections.Generic;
using Friflo.Json.Fliox;
using System;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace EntityIdStore2.Client {

public abstract class EntityIdStore {
    [RequiredField]
    Dictionary<string, GuidEntity>       guidEntities;
    [RequiredField]
    Dictionary<string, IntEntity>        intEntities;
    [RequiredField]
    Dictionary<string, AutoIntEntity>    intEntitiesAuto;
    [RequiredField]
    Dictionary<string, LongEntity>       longEntities;
    [RequiredField]
    Dictionary<string, ShortEntity>      shortEntities;
    [RequiredField]
    Dictionary<string, ByteEntity>       byteEntities;
    [RequiredField]
    Dictionary<string, CustomIdEntity>   customIdEntities;
    [RequiredField]
    Dictionary<string, EntityRefs>       entityRefs;
    [RequiredField]
    Dictionary<string, CustomIdEntity2>  customIdEntities2;
}

public class GuidEntity {
    Guid  id;
}

public class IntEntity {
    int  id;
}

public class AutoIntEntity {
    int  id;
}

public class LongEntity {
    [PrimaryKey]
    long  Id;
}

public class ShortEntity {
    short  id;
}

public class ByteEntity {
    byte  id;
}

public class CustomIdEntity {
    [PrimaryKey]
    [RequiredField]
    string  customId;
}

public class EntityRefs {
    [RequiredField]
    string      id;
    Guid        guidEntity;
    Guid?       guidNullEntity;
    int         intEntity;
    int?        intNullEntity;
    int?        intNullEntity2;
    long        longEntity;
    long?       longNullEntity;
    short       shortEntity;
    short?      shortNullEntity;
    byte        byteEntity;
    byte?       byteNullEntity;
    string      customIdEntity;
    List<int>   intEntities;
    List<int?>  intNullEntities;
}

public class CustomIdEntity2 {
    [PrimaryKey]
    [RequiredField]
    string  customId2;
}

}

