
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8011/fliox

###
PUT {{base}}/rest
Cookie: {{auth}}

###
GET {{base}}/rest/main_db//article-1
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/foo/?cmd=bar
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/foo/?cmd=bar
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/foo/?msg=bar
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/foo/?msg=bar
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/?cmd=std.Echo&param=invalid
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/articles/invalidOperation
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles/article-1/invalid
Cookie: {{auth}}

###
DELETE {{base}}/rest/main_db/articles
Cookie: {{auth}}

###
PUT {{base}}/rest/main_db
Cookie: {{auth}}

###
PUT {{base}}/rest/main_db/articles
Cookie: {{auth}}

Invalid Json

###
PUT {{base}}/rest/main_db/articles?create=invalid
Cookie: {{auth}}

{ }

###
PATCH {{base}}/rest/main_db
Cookie: {{auth}}

{}

###
PATCH {{base}}/rest/main_db/articles
Cookie: {{auth}}

{}

###
PATCH {{base}}/rest/main_db/articles/invalid-patch
Cookie: {{auth}}

Invalid Patch

###
PATCH {{base}}/rest/main_db/articles/article-abc
Cookie: {{auth}}

{
    "id": "article-xyz",
    "name": "Foo"
}

###
PATCH {{base}}/rest/main_db/articles/article-missing-id
Cookie: {{auth}}

{
    "name": "Foo"
}


###
PATCH {{base}}/rest/main_db/articles/article-1
Cookie: {{auth}}

{
    "id": "article-1",
    "name": 12345
}

###
PATCH {{base}}/rest/main_db/articles/missing-article
Cookie: {{auth}}

{
    "id": "missing-article",
    "name": "missing article"
}

###
HEAD {{base}}/rest/main_db
Cookie: {{auth}}


