
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox

###
POST {{base}}/rest/main_db/?command=std.Echo
Cookie: {{auth}}

{ "hello": "world" }

###
GET {{base}}/rest/main_db/?command=std.Echo&param="hello"
Cookie: {{auth}}

###
GET {{base}}/rest/main_db?command=std.Containers
Cookie: {{auth}}

###
GET {{base}}/rest/main_db?command=std.Messages
Cookie: {{auth}}

###
GET {{base}}/rest/main_db?command=std.Host
Cookie: {{auth}}

###
GET {{base}}/rest/main_db?command=std.User
Cookie: {{auth}}
