
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox

###
GET {{base}}/rest/main_db/articles/article-1
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/?msg=Message1
Cookie: {{auth}}

"foo"

###
GET {{base}}/rest
Cookie: {{auth}}

###
GET {{base}}/rest/main_db
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?orderByKey=asc
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles/article-1
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?filter=o=>o.producer=='producer-samsung'&orderByKey=asc
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?ids=article-1,article-2
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/articles/bulk-get
Cookie: {{auth}}

["article-1","article-2"]

###
POST {{base}}/rest/main_db/articles/bulk-get
Cookie: {{auth}}

[1,2]
