
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8011/fliox

###
PUT {{base}}/rest/main_db/articles/article-PUT-single
Cookie: {{auth}}

{
    "id": "article-PUT-single",
    "name": "PUT new Article",
    "producer": "producer-samsung"
}

###
PUT {{base}}/rest/main_db/articles
Cookie: {{auth}}

[{
    "id": "article-new",
    "name": "New Article",
    "producer": "producer-samsung"
}]

###
PATCH {{base}}/rest/main_db/articles/article-ipad
Cookie: {{auth}}

{
    "id": "article-ipad",
    "name": "patched via REST"
}

###
PATCH {{base}}/rest/main_db/articles
Cookie: {{auth}}

[{
    "id": "article-2",
    "name": "patched via REST"
}]

###
DELETE {{base}}/rest/main_db/articles/article-1
Cookie: {{auth}}

###
POST {{base}}/rest/main_db/articles/bulk-delete
Cookie: {{auth}}

["article-2"]
