
@auth = fliox-user=admin; fliox-token=admin
@base = http://localhost:8010/fliox


###
PUT {{base}}/rest/cluster/articles
Cookie: {{auth}}

[]

###
PUT {{base}}/rest/main_db/articles
Cookie: {{auth}}

[{ "id": "xxx" }]

###
POST {{base}}/rest/main_db?cmd=UnknownCommand
Cookie: {{auth}}

###
POST {{base}}/rest/main_db?cmd=test.CommandExecutionError
Cookie: {{auth}}

###
POST {{base}}/rest/main_db?cmd=test.CommandExecutionException
Cookie: {{auth}}



###
GET {{base}}/rest/main_db/articles?filter=abc
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?filter=1-2
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?filter-tree=invalid
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?filter-tree={"op":"false"}
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?filter-tree={"op":"equal","left":{"op":"field","name":"xxx.name"},"right":{"op":"string","value":"Smartphone"}}
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?maxCount=invalid
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?limit=invalid
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?cursor=unknown
Cookie: {{auth}}

###
GET {{base}}/rest/main_db/articles?maxCount=1
Cookie: {{auth}}
