not used anymore. Replaced by: https://github.com/friflo/Friflo.Engine.ECS/blob/main/.github/workflows/engine.yml

name: CI-Engine

on:
  push:
    branches: [ engine ]
  pull_request:
    branches: [ engine ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101

    - name: Restore dependencies
      working-directory: ./Engine
      run: dotnet restore

    - name: Build
      working-directory: ./Engine
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./Engine
      run: dotnet test --no-build --verbosity normal




    