@base = http://localhost:8011/fliox

###
GET {{base}}/rest/cluster/containers
Cookie: fliox-user=admin; fliox-token=admin

###
GET {{base}}/rest/cluster/containers
Cookie: fliox-user=monitor-admin; fliox-token=monitor-admin

###
GET {{base}}/rest/cluster/containers
Cookie: fliox-user=user-admin; fliox-token=user-admin

###
GET {{base}}/rest/cluster/containers
Cookie: fliox-user=user-readonly; fliox-token=user-readonly