// Generated by: https://github.com/friflo/Friflo.Json.Fliox#schema
using System.Collections.Generic;
using Friflo.Json.Fliox.Mapper;
using System;
using System.Numerics;

#pragma warning disable 0169 // [CS0169] The field '...' is never used

namespace PocStore2.Client {

public abstract class PocStore {
    [Fri.RequiredMember]
    Dictionary<string, Order>     orders;
    [Fri.RequiredMember]
    Dictionary<string, Customer>  customers;
    [Fri.RequiredMember]
    Dictionary<string, Article>   articles;
    [Fri.RequiredMember]
    Dictionary<string, Producer>  producers;
    [Fri.RequiredMember]
    Dictionary<string, Employee>  employees;
    [Fri.RequiredMember]
    Dictionary<string, TestType>  types;
}

public class Order {
    [Fri.RequiredMember]
    string           id;
    string           customer;
    DateTime         created;
    List<OrderItem>  items;
}

public class Customer {
    [Fri.RequiredMember]
    string  id;
    [Fri.RequiredMember]
    string  name;
}

public class Article {
    [Fri.RequiredMember]
    string  id;
    [Fri.RequiredMember]
    string  name;
    string  producer;
}

public class Producer {
    [Fri.RequiredMember]
    string        id;
    [Fri.RequiredMember]
    string        name;
    List<string>  employees;
}

public class Employee {
    [Fri.RequiredMember]
    string  id;
    [Fri.RequiredMember]
    string  firstName;
    string  lastName;
}

public class TestType : PocEntity {
    DateTime      dateTime;
    DateTime?     dateTimeNull;
    BigInteger    bigInt;
    BigInteger?   bigIntNull;
    bool          boolean;
    bool?         booleanNull;
    byte          uint8;
    byte?         uint8Null;
    short         int16;
    short?        int16Null;
    int           int32;
    int?          int32Null;
    long          int64;
    long?         int64Null;
    float         float32;
    float?        float32Null;
    double        float64;
    double?       float64Null;
    PocStruct     pocStruct;
    PocStruct?    pocStructNull;
    [Fri.RequiredMember]
    List<int>     intArray;
    List<int>     intArrayNull;
    List<int?>    intNullArray;
    JsonValue?    jsonValue;
    [Fri.RequiredMember]
    DerivedClass  derivedClass;
    DerivedClass  derivedClassNull;
}

public class OrderItem {
    [Fri.RequiredMember]
    string  article;
    int     amount;
    string  name;
}

public abstract class PocEntity {
    [Fri.RequiredMember]
    string  id;
}

public struct PocStruct {
    int  value;
}

public class DerivedClass : OrderItem {
    int  derivedVal;
}

public class TestCommand {
    string  text;
}

}

